CREATE TABLE IF NOT EXISTS telegram_file_uploads (
    job_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    telegram_chat_id BIGINT NOT NULL,
    remote_directory VARCHAR(1024) NOT NULL,
    requested_filename VARCHAR(255) NOT NULL,
    target_filename VARCHAR(255) NULL,
    collision_policy VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'queued',
    reported_size BIGINT UNSIGNED NULL,
    actual_size BIGINT UNSIGNED NULL,
    checksum_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    notification_id BIGINT UNSIGNED NULL,
    last_error_code VARCHAR(100) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    completed_at DATETIME NULL,
    INDEX idx_telegram_upload_owner (user_id, account_id, created_at),
    INDEX idx_telegram_upload_status (status, updated_at),
    CONSTRAINT fk_telegram_upload_job FOREIGN KEY (job_id) REFERENCES queue_jobs(id) ON DELETE CASCADE,
    CONSTRAINT fk_telegram_upload_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_telegram_upload_account FOREIGN KEY (account_id) REFERENCES cpanel_accounts(id) ON DELETE CASCADE,
    CONSTRAINT fk_telegram_upload_notification FOREIGN KEY (notification_id) REFERENCES notifications(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
