CREATE TABLE IF NOT EXISTS file_archive_jobs (
    job_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    operation VARCHAR(20) NOT NULL,
    sources_json LONGTEXT NULL,
    archive_path VARCHAR(1024) NOT NULL,
    destination VARCHAR(1024) NOT NULL,
    format VARCHAR(20) NULL,
    collision_policy VARCHAR(20) NOT NULL DEFAULT 'reject',
    status VARCHAR(40) NOT NULL DEFAULT 'queued',
    validation_json LONGTEXT NULL,
    reconciliation_json LONGTEXT NULL,
    reconciled TINYINT(1) NOT NULL DEFAULT 0,
    notification_id BIGINT UNSIGNED NULL,
    last_error_code VARCHAR(100) NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_file_archive_owner (user_id, account_id, created_at),
    INDEX idx_file_archive_status (status, updated_at),
    CONSTRAINT fk_file_archive_job FOREIGN KEY (job_id) REFERENCES queue_jobs(id) ON DELETE CASCADE,
    CONSTRAINT fk_file_archive_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_file_archive_account FOREIGN KEY (account_id) REFERENCES cpanel_accounts(id) ON DELETE CASCADE,
    CONSTRAINT fk_file_archive_notification FOREIGN KEY (notification_id) REFERENCES notifications(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
