<?php

declare(strict_types=1);

namespace App\Core;

use RuntimeException;

/** Atomic, permission-restricted writer for the generated .env file. */
final class EnvFile
{
    /** @param array<string,string> $values */
    public static function write(string $path, array $values, string $header = 'Generated by Telegram cPanel Manager'): void
    {
        $lines = ['# ' . $header . ' on ' . gmdate('c')];
        foreach ($values as $key => $value) {
            $lines[] = self::line($key, $value);
        }
        self::replace($path, implode(PHP_EOL, $lines) . PHP_EOL);
    }

    /**
     * Updates or appends keys while preserving every other line.
     *
     * @param array<string,string> $changes
     */
    public static function update(string $path, array $changes): void
    {
        $existing = is_file($path) ? file($path, FILE_IGNORE_NEW_LINES) : [];
        if ($existing === false) {
            throw new RuntimeException('Configuration file cannot be read.');
        }
        $pending = $changes;
        foreach ($existing as $index => $line) {
            if (preg_match('/^\s*([A-Z][A-Z0-9_]*)\s*=/', $line, $match) && array_key_exists($match[1], $pending)) {
                $existing[$index] = self::line($match[1], $pending[$match[1]]);
                unset($pending[$match[1]]);
            }
        }
        foreach ($pending as $key => $value) {
            $existing[] = self::line($key, $value);
        }
        self::replace($path, implode(PHP_EOL, $existing) . PHP_EOL);
    }

    private static function line(string $key, string $value): string
    {
        if (!preg_match('/^[A-Z][A-Z0-9_]*$/', $key)) {
            throw new RuntimeException('Configuration key is invalid.');
        }
        if (str_contains($value, "\n") || str_contains($value, "\r") || str_contains($value, "\0")) {
            throw new RuntimeException('Configuration value contains a line break.');
        }
        return $key . '=' . $value;
    }

    private static function replace(string $path, string $content): void
    {
        $directory = dirname($path);
        $temporary = $directory . '/.env.tmp-' . bin2hex(random_bytes(6));
        if (@file_put_contents($temporary, $content, LOCK_EX) === false) {
            throw new RuntimeException('Configuration file could not be written.');
        }
        @chmod($temporary, 0600);
        if (!@rename($temporary, $path)) {
            // Some shared hosts forbid rename over an existing file; fall back to an in-place write.
            @unlink($temporary);
            if (@file_put_contents($path, $content, LOCK_EX) === false) {
                throw new RuntimeException('Configuration file could not be installed.');
            }
        }
        @chmod($path, 0600);
    }
}
